require 'stringio'
require 'test/unit'
require 'inline'
require 'PDF/Writer'
require 'iconv'
require File.dirname(__FILE__) + '/../lib/cloud/cloud.rb'
require File.dirname(__FILE__) + '/../lib/cloud/wordbox.rb'